name = "acik-teklif-pazari"
main = "src/worker.ts"
compatibility_date = "2025-02-14"
workers_dev = true

routes = [
  { pattern = "kamutas.com", custom_domain = true }
]

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "acik-teklif-pazari-db"
database_id = "bccf8580-72c9-42dd-af17-31a9b5b332d8"
migrations_dir = "migrations"

[vars]
ENVIRONMENT = "production"
REQUIRE_EMAIL_VERIFICATION = "false"
REQUIRE_TURNSTILE = "false"
ADMIN_EMAILS = "gokcek@outlook.com"
ADMIN_BOOTSTRAP_EMAIL = "gokcek@outlook.com"
ADMIN_BOOTSTRAP_PASSWORD = "123456"
